---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup-controller.rclsilver-org.github.com
  resources:
  - policies
  - schedules
  verbs:
  - get
  - list
  - watch
