# This rule is not used by the project backup-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over backup-controller.rclsilver-org.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-controller
    app.kubernetes.io/managed-by: kustomize
  name: schedule-admin-role
rules:
- apiGroups:
  - backup-controller.rclsilver-org.github.com
  resources:
  - schedules
  verbs:
  - '*'
- apiGroups:
  - backup-controller.rclsilver-org.github.com
  resources:
  - schedules/status
  verbs:
  - get
